### ISSUE TITLE
Unable to change current working directory.

### ISSUE THREAD

**Issue by xoorath** [pCYSl5EDgo/create-unitypackage#7]
Hey,

My unity project is not the root of the git repo. I can generate a unity package (example: https://github.com/xoorath/xo-unity-spaces/actions/runs/5919493049) but the package itself is not valid. 

When inspecting the contents of the package I'm seeing paths like `<reponame>/Assets/<inner folder>` which is leading me to suspect that the root folder must be the unity project directory in order for this action to work properly. 

I've tried changing the working directory of the _echo to file_ steps but the package can not be created: https://github.com/xoorath/xo-unity-spaces/actions/runs/5919565716

The errors produced:
```
[Error: ENOENT: no such file or directory, open 'Assets/xo-unity-spaces.meta'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Assets/xo-unity-spaces.meta'
}
```

I'm not sure if this issue is a duplicate of #5.

If I'm right about the issue I would recommend adding a way to change the current working directory or specifying a unity project path.

**Comment by xoorath** [comment]
I was able to resolve the issue locally by moving my unity project root to the repo root: https://github.com/xoorath/xo-unity-spaces/actions/runs/5919627244

I don't think this will be a good solution for others - but it will work for me.

**Comment by pCYSl5EDgo** [comment]
[v1.2.1](https://github.com/pCYSl5EDgo/create-unitypackage/releases/tag/v1.2.1) supports changing current directory.
I hope this version will help you.
