### ISSUE TITLE
Build failing on latest version

### ISSUE THREAD

**Issue by endel** [pCYSl5EDgo/create-unitypackage#9]
Hi @pCYSl5EDgo, I've been using your action for quite a while and it has been very useful! Thank you for this!

I noticed my build [started to fail](https://github.com/colyseus/colyseus-unity-sdk/actions/runs/7478890915/job/20354894745) using the recent updates, though:

![image](https://github.com/pCYSl5EDgo/create-unitypackage/assets/130494/1dccaa3d-33d4-4fc7-b3d8-43971ee21e2c)

I've just reverted back to use `v1.1.1` and the [build succeeded](https://github.com/colyseus/colyseus-unity-sdk/actions/runs/7478980600/job/20355156149). 

I haven't debugged deeply to understand what happened, do you have any clues? Cheers!

**Comment by pCYSl5EDgo** [comment]
@endel 
Hi. I've fixed the bug and published [v1.2.3](https://github.com/pCYSl5EDgo/create-unitypackage/releases/tag/v1.2.3).
Thank you for using this action.
